# Generated by Django 4.1 on 2022-08-06 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Meme',
            },
        ),
        migrations.CreateModel(
            name='TagList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_names', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'TagList',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30)),
                ('score', models.PositiveIntegerField()),
                ('attached_meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='sites.meme')),
            ],
            options={
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Mi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('favorite_meme', models.ManyToManyField(related_name='liked_by', to='sites.meme')),
            ],
            options={
                'db_table': 'Mi',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=30)),
                ('possibility', models.PositiveIntegerField()),
                ('attached_meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='sites.meme')),
            ],
            options={
                'db_table': 'Language',
            },
        ),
        migrations.CreateModel(
            name='Evalutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_diff', models.IntegerField()),
                ('evaluated_time', models.DateTimeField(auto_now_add=True)),
                ('evaluated_meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='sites.meme')),
                ('evaluated_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='sites.tag')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='sites.mi')),
            ],
            options={
                'db_table': 'Evaluation',
            },
        ),
    ]
