# Generated by Django 4.1 on 2022-08-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='possibility',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='score',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
