# Generated by Django 4.1 on 2022-08-06 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_language_possibility_alter_tag_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='uploaded_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
