# Generated by Django 4.1 on 2022-08-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_rename_evalutation_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mi',
            name='favorite_meme',
            field=models.ManyToManyField(default=1, related_name='liked_by', to='sites.meme'),
        ),
    ]
