# Generated by Django 4.1 on 2022-08-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_alter_mi_favorite_meme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mi',
            name='favorite_meme',
            field=models.ManyToManyField(related_name='liked_by', to='sites.meme'),
        ),
    ]
