# Generated by Django 4.1 on 2022-08-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_alter_mi_favorite_meme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mi',
            name='favorite_meme',
            field=models.ManyToManyField(null=True, related_name='liked_by', to='sites.meme'),
        ),
    ]
