# Generated by Django 4.1 on 2022-08-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_alter_mi_favorite_meme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mi',
            old_name='favorite_meme',
            new_name='favorite_memes',
        ),
    ]
